import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/HeaderComponent';
import Footer from '@/components/FooterComponent';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Next.js E-commerce',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className} suppressHydrationWarning>
        <div className='container'>
          <Header />
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
